const ParkingActionTypes={
    FETCH_PARKING_START:'FETCH_PARKING_START',
    FETCH_PARKING_SUCCESS:'FETCH_PARKING_SUCCESS',
    FETCH_PARKING_FAILURE:'FETCH_PARKING_FAILURE',
    SET_PARKING_ZONE:'SET_PARKING_ZONE'
}

export default ParkingActionTypes;