const UserActionTypes={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS'
}

export default UserActionTypes;